apiVersion: v1
kind: ConfigMap
metadata:
  name: snmp-exporter-config
data:
  snmp.yml: |
    modules:
      cisco:
        walk:
          - 1.3.6.1.2.1.1        # system
          - 1.3.6.1.2.1.2        # interfaces
        version: 2c
        auth:
          community: public
