apiVersion: v1
kind: Secret
metadata:
  name: influxdb-credentials
  namespace: monitoring
type: Opaque
data:
  token: ZVFYZ1ZDOTVXNG4wT2ZucE01dzZMekZJZ0dOT3BHU2tJV0xXOEl3RVN5T3JkelFVbTBoVTEwYUtOS1VvdmJZZFpScnBBNVpnWTR6NkNMYTA4U3Nwa0E9PQ==
