apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  namespace: monitoring
data:
  telegraf.conf: |
    [agent]
      interval = "60s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "60s"
      flush_jitter = "0s"
      precision = ""
      hostname = ""
      omit_hostname = true

    [[outputs.influxdb_v2]]
      urls = ["http://influxdb.monitoring.svc.cluster.local:8086"]
      token = "$INFLUX_TOKEN"
      organization = "virtualelephant"
      bucket = "snmp"

    [[inputs.snmp]]
      agents = [ "10.1.100.2:161", "10.1.100.3:161", "10.1.100.253:161" ]
      version = 3
      sec_name = "telegraf-snmp"
      auth_protocol = "MD5"
      auth_password = "$AUTH_PASS"
      priv_protocol = "DES"
      priv_password = "$PRIV_PASS"
      sec_level = "authPriv"
      name_prefix = "snmp_"

      [[inputs.snmp.field]]
        name = "hostname"
        oid = "SNMPv2-MIB::sysName.0"
      [[inputs.snmp.field]]
        name = "uptime"
        oid = "DISMAN-EVENT-MIB::sysUpTimeInstance"
      [[inputs.snmp.table]]
        name = "interface"
        oid = "IF-MIB::ifTable"
        inherit_tags = [ "hostname" ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  namespace: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - telegraf
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: telegraf
          image: telegraf:1.30
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: telegraf-config
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
          env:
            - name: INFLUX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-credentials
                  key: token
            - name: AUTH_PASS
              valueFrom:
                secretKeyRef:
                  name: snmp-credentials
                  key: auth_password
            - name: PRIV_PASS
              valueFrom:
                secretKeyRef:
                  name: snmp-credentials
                  key: priv_password
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-config
