influxdb:
  url: "http://influxdb.home.virtualelephant.com"
  token: "0gcx04iY-ifLsC9mwzfOq86v_tDsUXceoetzOb8M4z-ZOLckrntLwF2IFs9oGieXUi1Om2aPoj3bYPaczqMXjw=="
  org: "virtualelephant"
  bucket: "monitoring"

poll_interval_minutes: 1
