apiVersion: batch/v1
kind: CronJob
metadata:
  name: fping-monitor-cron
  namespace: monitoring
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: fping
            image: harbor.home.virtualelephant.com/ve-lab/fping-monitor:latest
            env:
            - name: INFLUX_URL
              value: "http://influxdb.home.virtualelephant.com"
            - name: INFLUX_BUCKET
              value: "monitoring"
            - name: INFLUX_ORG
              value: "virtualelephant"
            - name: INFLUX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-fping-token
                  key: token
          restartPolicy: OnFailure
