---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codellama-ingress
  namespace: codellama
  annotations:
    ingress.class: "haproxy"
spec:
  rules:
  - host: codellama-backend.home.virtualelephant.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: codellama-service
            port:
              number: 80
              