apiVersion: batch/v1
kind: CronJob
metadata:
  name: codellama-fine-tune-cron
  namespace: codellama
spec:
  schedule: "0 0 * * 0" # Weekly on Sunday at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: extract
            image: harbor.home.virtualelephant.com/ve-lab/codellama-fine-tune:latest
            command: ["python", "extract_dataset.py"]
            env:
            - name: DB_HOST
              value: "postgres-service.codellama.svc.cluster.local"
            - name: DB_NAME
              value: "codellama"
            - name: DB_USER
              value: "codellama"
            - name: DB_PASSWORD
              value: "securepassword"
            - name: DB_PORT
              value: "5432"
            volumeMounts:
            - name: model-storage
              mountPath: /model
          - name: fine-tune
            image: harbor.home.virtualelephant.com/ve-lab/codellama-fine-tune:latest
            command: ["python", "fine_tune.py"]
            resources:
              requests:
                memory: "16Gi"
                cpu: "8"
              limits:
                memory: "32Gi"
                cpu: "16"
            env:
            - name: DB_HOST
              value: "postgres-service.default.svc.cluster.local"
            - name: DB_NAME
              value: "codellama"
            - name: DB_USER
              value: "codellama"
            - name: DB_PASSWORD
              value: "securepassword"
            - name: DB_PORT
              value: "5432"
            volumeMounts:
            - name: model-storage
              mountPath: /model
          volumes:
          - name: model-storage
            persistentVolumeClaim:
              claimName: codellama-pvc
          restartPolicy: Never
      backoffLimit: 1