apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: codellama
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-retain
  resources:
    requests:
      storage: 10Gi