apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch0
  namespace: kube-logging
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /opt/nfs/elasticsearch0
    server: 10.3.43.100
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch1
  namespace: kube-logging
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /opt/nfs/elasticsearch1
    server: 10.3.43.100
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch2
  namespace: kube-logging
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /opt/nfs/elasticsearch2
    server: 10.3.43.100
