apiVersion: v1
kind: PersistentVolume
metadata:
  name: kibana-elastic
  namespace: monitoring
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /opt/nfs/kibana
    server: 10.3.43.100
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kibana
  namespace: monitoring
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
