replicas: 1

ingress:
  enabled: false

hostname: rancher.home.virtualelephant.com

tls: external

persistence:
  enabled: true
  storageClass: standard-retain
  accessMode: ReadWriteOnce
  size: 8Gi

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "2"
    memory: "4Gi"

privateCA: false
