replicaCount: 1

elasticsearchHosts: "http://elasticsearch-master:9200"

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

service:
  type: ClusterIP
