prometheusOperator:
  enabled: true
  admissionWebhooks:
    enabled: true
  tls:
    enabled: true

prometheus:
  prometheusSpec:
    replicas: 2
    externalLabels:
      cluster: "ve-promtheus-cluster"
      replica: "${REPLICA}"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard-retain
          resources:
            requests:
              storage: 10Gi
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector:
      matchLabels:
        monitoring-stack: upstream
    serviceMonitorNamespaceSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}
    ruleSelectorNilUsesHelmValues: false
    ruleSelector: {}
    ruleNamespaceSelector: {}
    scrapeInterval: 30s
    evaluationInterval: 30s
    retention: 7d
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 4Gi
        cpu: "2"
    livenessProbe:
      httpGet:
        path: /-/healthy
        port: 9090
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /-/healthy
        port: 9090
      initialDelaySeconds: 5
      periodSeconds: 5

alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: standard-retain
          resources:
            requests:
              storage: 2Gi

grafana:
  persistence:
    enabled: true
    storageClassName: standard-retain
    size: 10Gi
  adminPassword: ChangeMe123!
  serviceMonitor:
    enabled: true
  defaultDashboardsTimezone: UTC-6
  resources:
    requests:
      cpu: 250m
      memory: 750Mi
    limits:
      cpu: 500m
      memory: 1Gi
  pod:
    livenessProbe:
      httpGet:
        path: /api/health
        port: 3000
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /api/health
        port: 3000
      initialDelaySeconds: 5
      periodSeconds: 5

rbac:
  create: true

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
