{
 "title": "Virtual Elephant / Home Lab / Cisco Devices",
 "tags": [
  "virtualelephant",
  "kubernetes",
  "prometheus",
  "influxdb"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Uplink Ethernet Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uplink to Spine (Ethernet1/49)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Ethernet1/49\" and\r\n    r._field == \"in_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 }))\r\n"
    },
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Ethernet1/49\" and\r\n    r._field == \"out_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 * -1.0 }))\r\n"
    }
   ]
  },
  {
   "title": "Uplink to pfSense (Ethernet1/48)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Ethernet1/48\" and\r\n    r._field == \"in_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 }))\r\n"
    },
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Ethernet1/48\" and\r\n    r._field == \"out_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 * -1.0 }))\r\n"
    }
   ]
  },
  {
   "title": "Uplink 1 to Synology (Ethernet1/43)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Ethernet1/43\" and\r\n    r._field == \"in_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 }))\r\n"
    },
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Ethernet1/43\" and\r\n    r._field == \"out_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 * -1.0 }))\r\n"
    }
   ]
  },
  {
   "title": "Uplink 1 to Synology (Ethernet1/44)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Ethernet1/44\" and\r\n    r._field == \"in_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 }))\r\n"
    },
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Ethernet1/44\" and\r\n    r._field == \"out_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 * -1.0 }))\r\n"
    }
   ]
  },
  { "title": "ESXi Ethernet Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "esxi01 (Ethernet1/3)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Ethernet1/3\" and\r\n    r._field == \"in_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 }))\r\n"
    },
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Ethernet1/3\" and\r\n    r._field == \"out_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 * -1.0 }))\r\n"
    }
   ]
  },
  {
   "title": "esxi02 (Ethernet1/5)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Ethernet1/5\" and\r\n    r._field == \"in_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 }))\r\n"
    },
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Ethernet1/5\" and\r\n    r._field == \"out_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 * -1.0 }))\r\n"
    }
   ]
  },
  {
   "title": "esxi03 (Ethernet1/7)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Ethernet1/7\" and\r\n    r._field == \"in_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 }))\r\n"
    },
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Ethernet1/7\" and\r\n    r._field == \"out_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 * -1.0 }))\r\n"
    }
   ]
  },
  {
   "title": "esxi04 (Ethernet1/9)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Ethernet1/9\" and\r\n    r._field == \"in_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 }))\r\n"
    },
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Ethernet1/9\" and\r\n    r._field == \"out_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 * -1.0 }))\r\n"
    }
   ]
  },
  {
   "title": "esxi05 (Ethernet1/11)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Ethernet1/11\" and\r\n    r._field == \"in_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 }))\r\n"
    },
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Ethernet1/11\" and\r\n    r._field == \"out_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 * -1.0 }))\r\n"
    }
   ]
  },
  { "title": "VLAN Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "VLAN 10 (User)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Vlan10\" and\r\n    r._field == \"in_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 }))\r\n"
    },
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Vlan10\" and\r\n    r._field == \"out_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 * -1.0 }))\r\n"
    }
   ]
  },
  {
   "title": "VLAN 11 (iSCSI)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Vlan11\" and\r\n    r._field == \"in_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 }))\r\n"
    },
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Vlan11\" and\r\n    r._field == \"out_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 * -1.0 }))\r\n"
    }
   ]
  },
  {
   "title": "VLAN 12 (iSCSI)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Vlan12\" and\r\n    r._field == \"in_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 }))\r\n"
    },
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Vlan12\" and\r\n    r._field == \"out_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 * -1.0 }))\r\n"
    }
   ]
  },
  {
   "title": "VLAN 210 (VM Management)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Vlan210\" and\r\n    r._field == \"in_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 }))\r\n"
    },
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Vlan210\" and\r\n    r._field == \"out_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 * -1.0 }))\r\n"
    }
   ]
  },
  {
   "title": "VLAN 211 (Host Management)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Vlan211\" and\r\n    r._field == \"in_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 }))\r\n"
    },
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Vlan211\" and\r\n    r._field == \"out_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 * -1.0 }))\r\n"
    }
   ]
  },
  {
   "title": "VLAN 212 (vMotion)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Vlan212\" and\r\n    r._field == \"in_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 }))\r\n"
    },
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Vlan212\" and\r\n    r._field == \"out_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 * -1.0 }))\r\n"
    }
   ]
  },
  {
   "title": "VLAN 213 (vSAN)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Vlan213\" and\r\n    r._field == \"in_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 }))\r\n"
    },
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Vlan213\" and\r\n    r._field == \"out_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 * -1.0 }))\r\n"
    }
   ]
  },
  {
   "title": "VLAN 611 (Overlay Network 1)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Vlan611\" and\r\n    r._field == \"in_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 }))\r\n"
    },
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Vlan611\" and\r\n    r._field == \"out_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 * -1.0 }))\r\n"
    }
   ]
  },
  {
   "title": "VLAN 612 (Overlay Network 2)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Vlan612\" and\r\n    r._field == \"in_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 }))\r\n"
    },
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"cisco_devices\" and\r\n    (r.device == \"10.1.10.2\" or r.device == \"10.1.10.3\") and\r\n    r.interface == \"Vlan612\" and\r\n    r._field == \"out_octets\"\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 8.0 / 1000000.0 * -1.0 }))\r\n"
    }
   ]
  }
 ]
}