{
 "title": "Virtual Elephant / Home Lab / Linux Hosts",
 "tags": [
  "virtualelephant",
  "linux",
  "influxdb"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"monitoring\",\r\n  tag: \"host\",\r\n  predicate: (r) => r._measurement == \"system_metrics\",\r\n  start: -30d\r\n)\r\n"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview - All Hosts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage - All Hosts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"system_metrics\" and\r\n    r._field == \"cpu_percent_total\"\r\n  )\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    _field: strings.replaceAll(v: r.host, t: \".home.virtualelephant.com\", u: \"\")\r\n  }))\r\n  |> yield(name: \"cpu_percent_total_all_hosts_short\")\r\n"
    }
   ]
  },
  { "title": "CPU Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "1m Load Avg for $hostname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"system_metrics\" and\r\n    r._field == \"load_avg_1m\" and\r\n    r.host =~ /^$hostname$/\r\n  )\r\n  |> yield(name: \"load_avg_1m\")\r\n"
    }
   ]
  },
  {
   "title": "5m Load Avg for $hostname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"system_metrics\" and\r\n    r._field == \"load_avg_5m\" and\r\n    r.host =~ /^$hostname$/\r\n  )\r\n  |> yield(name: \"load_avg_5m\")\r\n"
    }
   ]
  },
  {
   "title": "15m Load Avg for $hostname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"system_metrics\" and\r\n    r._field == \"load_avg_15m\" and\r\n    r.host =~ /^$hostname$/\r\n  )\r\n  |> yield(name: \"load_avg_15m\")\r\n"
    }
   ]
  },
  {
   "title": "CPU Core Usage for $hostname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"system_metrics\" and\r\n    r._field == \"cpu_core_0_percent\" and\r\n    r.host =~ /^$hostname$/\r\n  )\r\n  |> yield(name: \"cpu_core_0\")"
    },
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"system_metrics\" and\r\n    r._field == \"cpu_core_1_percent\" and\r\n    r.host =~ /^$hostname$/\r\n  )\r\n  |> yield(name: \"cpu_core_1\")"
    },
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"system_metrics\" and\r\n    r._field == \"cpu_core_2_percent\" and\r\n    r.host =~ /^$hostname$/\r\n  )\r\n  |> yield(name: \"cpu_core_2\")"
    },
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"system_metrics\" and\r\n    r._field == \"cpu_core_3_percent\" and\r\n    r.host =~ /^$hostname$/\r\n  )\r\n  |> yield(name: \"cpu_core_3\")"
    }
   ]
  },
  {
   "title": "CPU Total Core Usage for $hostname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"system_metrics\" and\r\n    r._field == \"cpu_percent_total\" and\r\n    r.host =~ /^$hostname$/\r\n  )\r\n  |> yield(name: \"cpu_percent_total_single_host\")\r\n"
    }
   ]
  },
  {
   "title": "Memory Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"system_metrics\" and\r\n    r._field == \"memory_percent\" and\r\n    r.host =~ /^$hostname$/\r\n  )\r\n  |> yield(name: \"memory_percent\")\r\n"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"system_metrics\" and\r\n    r._field == \"memory_total_mb\" and\r\n    r.host =~ /^$hostname$/\r\n  )\r\n  |> yield(name: \"memory_total_mb\")\r\n"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"system_metrics\" and\r\n    r._field == \"memory_free_mb\" and\r\n    r.host =~ /^$hostname$/\r\n  )\r\n  |> yield(name: \"memory_free_mb\")\r\n"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"system_metrics\" and\r\n    r._field == \"memory_used_mb\" and\r\n    r.host =~ /^$hostname$/\r\n  )\r\n  |> yield(name: \"memory_used_mb\")\r\n"
      }
     ]
    },
    {
     "title": "Memory Used & Free in MB for $hostname",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"system_metrics\" and\r\n    r._field == \"memory_free_mb\" and\r\n    r.host =~ /^$hostname$/\r\n  )\r\n  |> yield(name: \"memory_free_mb\")\r\n"
      },
      {
       "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"system_metrics\" and\r\n    r._field == \"memory_used_mb\" and\r\n    r.host =~ /^$hostname$/\r\n  )\r\n  |> yield(name: \"memory_used_mb\")\r\n"
      }
     ]
    },
    {
     "title": "Memory Percent for $hostname",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"system_metrics\" and\r\n    r._field == \"memory_percent\" and\r\n    r.host =~ /^$hostname$/\r\n  )\r\n  |> yield(name: \"memory_free_mb\")\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Packets per second for $hostname",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"system_metrics\" and\r\n    r._field == \"network_packets_recv\" and\r\n    r.host =~ /^$hostname$/\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> yield(name: \"network_packets_recv_per_sec\")\r\n"
      },
      {
       "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"system_metrics\" and\r\n    r._field == \"network_packets_sent\" and\r\n    r.host =~ /^$hostname$/\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: r._value * -1.0 }))\r\n  |> yield(name: \"network_packets_sent_per_sec_inverted\")\r\n"
      }
     ]
    },
    {
     "title": "Network Traffic MB/sec for $hostname",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "query": "import \"math\"\r\n\r\nfrom(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"system_metrics\" and\r\n    r._field == \"network_bytes_sent\" and\r\n    r.host =~ /^$hostname$/\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 1048576.0 * -1.0 }))\r\n  |> yield(name: \"network_bytes_sent_MB_per_sec\")\r\n"
      },
      {
       "query": "import \"math\"\r\n\r\nfrom(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"system_metrics\" and\r\n    r._field == \"network_bytes_recv\" and\r\n    r.host =~ /^$hostname$/\r\n  )\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 1048576.0 }))\r\n  |> yield(name: \"network_bytes_recv_MB_per_sec\") \r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "type": "gauge",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"system_metrics\" and\r\n    r.host =~ /^$hostname$/ and\r\n    r._field == \"disk_usage_percent\"\r\n  )\r\n  |> yield(name: \"disk_usage_percent\")\r\n"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"system_metrics\" and\r\n    r.host =~ /^$hostname$/ and\r\n    r._field == \"disk_used_gb\"\r\n  )\r\n  |> yield(name: \"disk_used_gb\")\r\n"
      }
     ]
    },
    {
     "title": "Disk Performance for $hostname",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "query": "import \"math\"\r\n\r\nfrom(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"system_metrics\" and\r\n    r.host =~ /^$hostname$/ and\r\n    r._field == \"disk_read_bytes\"\r\n  )\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 1048576.0 * -1.0 }))\r\n  |> yield(name: \"disk_read_mb_per_s\")\r\n\r\n\r\n"
      },
      {
       "query": "import \"math\"\r\n\r\nfrom(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"system_metrics\" and\r\n    r.host =~ /^$hostname$/ and\r\n    r._field == \"disk_write_bytes\"\r\n  )\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 1048576.0 }))\r\n  |> yield(name: \"disk_write_mb_per_s\")\r\n"
      }
     ]
    },
    {
     "title": "Disk Write Performance for $hostname",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "query": "import \"math\"\r\n\r\nfrom(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"system_metrics\" and\r\n    r.host =~ /^$hostname$/ and\r\n    r._field == \"disk_write_bytes\"\r\n  )\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 1048576.0 }))\r\n  |> yield(name: \"disk_write_mb_per_s\")\r\n"
      }
     ]
    },
    {
     "title": "Disk Read Performance for $hostname",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "query": "import \"math\"\r\n\r\nfrom(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"system_metrics\" and\r\n    r.host =~ /^$hostname$/ and\r\n    r._field == \"disk_read_bytes\"\r\n  )\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 1048576.0 }))\r\n  |> yield(name: \"disk_read_mb_per_s\")\r\n\r\n\r\n"
      }
     ]
    },
    {
     "title": "Disk Usage in GB for $hostname",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 115 },
     "targets": [
      {
       "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"system_metrics\" and\r\n    r.host =~ /^$hostname$/ and\r\n    r._field == \"disk_total_gb\"\r\n  )\r\n  |> yield(name: \"disk_total_gb\")\r\n"
      },
      {
       "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"system_metrics\" and\r\n    r.host =~ /^$hostname$/ and\r\n    r._field == \"disk_free_gb\"\r\n  )\r\n  |> yield(name: \"disk_free_gb\")\r\n"
      }
     ]
    }
   ]
  }
 ]
}