- name: Ensure target namespace exists
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ item.namespace }}"
    state: present
  loop: "{{ helm_releases }}"
  loop_control:
    label: "{{ item.namespace }}"

- name: Add required Helm repositories
  community.kubernetes.helm_repository:
    name: "{{ item.repo_name }}"
    repo_url: "{{ item.repo_url }}"
  loop:
    - { repo_name: "prometheus-community", repo_url: "https://prometheus-community.github.io/helm-charts" }
    - { repo_name: "longhorn", repo_url: "https://charts.longhorn.io" }
    - { repo_name: "bitnami", repo_url: "https://charts.bitnami.com/bitnami" }
    - { repo_name: "elastic", repo_url: "https://helm.elastic.co" }

- name: Update Helm repositories
  command: helm repo update

- name: Deploy or upgrade Helm charts
  community.kubernetes.helm:
    name: "{{ item.name }}"
    chart_ref: "{{ item.chart }}"
    namespace: "{{ item.namespace }}"
    create_namespace: false
    values_files:
      - "{{ item.values_file }}"
    state: present
    wait: true
  loop: "{{ helm_releases }}"
