## File: argocd-values.yaml

global:
  image:
    tag: v2.11.3  # latest stable at time of writing

controller:
  replicas: 2
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
  metrics:
    enabled: true

repoServer:
  replicas: 2
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi

server:
  replicas: 2
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
  service:
    type: ClusterIP
  ingress:
    enabled: false
  tls:
    enabled: false
    secretName: wildcard-tls-secret
  extraArgs:
    - --insecure=true

applicationSet:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

notifications:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

redis:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

## Storage configuration for persistence
configs:
  cm:
    application.resourceTrackingMethod: annotation
    dex.config: |
      connectors:
        - type: ldap
          id: ldap
          name: LDAP
          config:
            host: ldap01.home.virtualelephant.com:389
            insecureNoSSL: true
            bindDN: uid=gitlab,ou=ServiceAccounts,dc=home,dc=virtualelephant,dc=com
            bindPWEnv: LDAP_BIND_PASSWORD
            usernamePrompt: Username
            userSearch:
              baseDN: ou=People,dc=home,dc=virtualelephant,dc=com
              filter: "(objectClass=person)"
              username: uid
              idAttr: uid
              emailAttr: mail
              nameAttr: cn
            groupSearch:
              baseDN: ou=Groups,dc=home,dc=virtualelephant,dc=com
              filter: "(objectClass=groupOfNames)"
              userAttr: DN
              groupAttr: member
              nameAttr: cn
  secret:
    create: true

dex:
  envFrom:
    - secretRef:
        name: argocd-ldap-secret

controller:
  persistence:
    enabled: true
    storageClass: standard-retain
    accessMode: ReadWriteOnce
    size: 8Gi

repoServer:
  persistence:
    enabled: true
    storageClass: standard-retain
    accessMode: ReadWriteOnce
    size: 8Gi
