apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: services
  annotations:
    ingress.class: "haproxy"
spec:
  tls:
  - hosts:
    - argocd.home.virtualelephant.com
    secretName: wildcard-tls-secret  # <-- Your wildcard cert secret

  rules:
  - host: argocd.home.virtualelephant.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80  # HTTPS internal
