apiVersion: apps/v1
kind: Deployment
metadata:
  name: synology-snmp-monitoring
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synology-snmp-monitoring
  template:
    metadata:
      labels:
        app: synology-snmp-monitoring
    spec:
      containers:
        - name: synology-snmp-agent
          image: harbor.home.virtualelephant.com/ve-lab/synology-snmp:latest
          imagePullPolicy: Always
          env:
            - name: SNMP_USER
              value: "deploy"
            - name: SNMP_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: synology-secret
                  key: SNMP_AUTH_KEY
            - name: SNMP_PRIV_KEY
              valueFrom:
                secretKeyRef:
                  name: synology-secret
                  key: SNMP_PRIV_KEY
            - name: INFLUX_URL
              value: "http://influxdb.home.virtualelephant.com"
            - name: INFLUX_ORG
              value: "virtualelephant"
            - name: INFLUX_BUCKET
              value: "monitoring"
            - name: INFLUX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-monitoring-token
                  key: token
            - name: TARGET_FILE
              value: "/app/synology_targets.txt"
            - name: POLL_INTERVAL_SECONDS
              value: "300"
          volumeMounts:
            - name: synology-targets
              mountPath: /app/synology_targets.txt
              subPath: synology_targets.txt
      volumes:
        - name: synology-targets
          configMap:
            name: synology-snmp-targets
