---
- name: Drain, Reboot, and Rejoin Kubernetes Node
  hosts: all
  become: true
  gather_facts: false

  vars:
    kubeconfig_path: admin.conf

  tasks:

    - name: Drain the Kubernetes node
      ansible.builtin.shell: |
        kubectl --kubeconfig {{ kubeconfig_path }} drain {{ inventory_hostname }} \
          --ignore-daemonsets --delete-emptydir-data --force
      delegate_to: localhost

    - name: Reboot the node
      ansible.builtin.reboot:
        reboot_timeout: 300

    - name: Wait for node to respond to ping
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        timeout: 300
        state: started

    - name: Wait for Kubernetes node to be Ready
      ansible.builtin.shell: |
        while [[ $(kubectl --kubeconfig {{ kubeconfig_path }} get nodes {{ inventory_hostname }} -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do
          echo "Waiting for node {{ inventory_hostname }} to become Ready..."
          sleep 10
        done
      delegate_to: localhost
      register: node_ready
      until: node_ready.rc == 0
      retries: 10
      delay: 15

    - name: Mark the node as schedulable
      ansible.builtin.shell: |
        kubectl --kubeconfig {{ kubeconfig_path }} uncordon {{ inventory_hostname }}
      delegate_to: localhost
