apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/deploy/.kube/dev-cluster-ca.crt
    server: https://10.5.1.13:6443
  name: dev
- cluster:
    certificate-authority: /home/deploy/.kube/stage-cluster-ca.crt
    server: https://10.5.1.15:6443
  name: stage
- cluster:
    certificate-authority: /home/deploy/.kube/prod-cluster-ca.crt
    server: https://10.5.1.17:6443
  name: prod

contexts:
- context:
    cluster: dev
    user: dev-haproxy-user
  name: dev
- context:
    cluster: stage
    user: stage-haproxy-user
  name: stage
- context:
    cluster: prod
    user: prod-haproxy-user
  name: prod

users:
- name: dev-haproxy-user
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ijl6YVNSRnZpaXNfdVBhTlc4cU5ldkp1b1RtNF9PV0IzdG5Cbm9TeTlNcjgifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJoYXByb3h5LXVzZXItdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiaGFwcm94eS11c2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMTA0NTZkZDQtNjNkMi00ZjljLWIxZDUtYzU4MzYyODFhYWRiIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmhhcHJveHktdXNlciJ9.eVXBcTKbN2aj-WoBdIuOuj4XQb1iSvfUC1CL5mp1tzw5KrAXErvzPxZOvtWzTqnz0icHT9VihZNrYgnjCcyk4KpZ7Mwj8R9xjNRVINV3E-gghNWPHHuqvLs76p_RckedJyTY87f1hzUCAhkYWsL72Ku4RaF10K94_dQoTeqxSAJspvM2DUoc8pS3_jq8cRn4Z3_eokPDCKMsHryRg6d32YcVWCc_LoVRyYxmX22lbpgcevz2n7dWDLBGm_G4D7Czz9ANdSkMjkUdxnBuZYpzRRKaC6lw1uXZgYBNVz0cnFSx6wAmKRfnfJU7-T8KVP0HNkwxthSO8Z0OdtfRvmG0TA
- name: stage-haproxy-user
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkZ3Z19yNHFvUlp6YmZxazdxdEdRWmszZ1gtZWltd2liOXBKVk5FbnNlTEUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJoYXByb3h5LXVzZXItdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiaGFwcm94eS11c2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZmM1Y2I3MWYtMWQ3NS00N2QyLTg1ZmMtOTlkMDc3YzljMzU4Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmhhcHJveHktdXNlciJ9.yp59dbQA0rW5487g3MYNKPu7d84xKv7lToKYYm-6KoGNe66Y3k9rIIfgtxUdbaXByr4uImOoGbPCMkxowRWpnAL9HzD2HCjwxL9KvNC3l_f2TL_ul1Va5rqAKnOlHwiXB1mcE-Nlh9GV29kDrCchKdoQjfZlas_b50HZUtgNoyNutH6pQwjq4DiPYGcO4Odg2jzB6LEw-vwWGHCqnhBYb6UID402qmEA0BOvmDQFndndEXPDtXGtUH62rORe3nE1MF_1ABSjKiSdBZ3cwrc_kUhQ9U16xiccAn8FsDMmMv5VbADqyUU3FaWPtvm0YGX-81jiNZKxcQsTHrwgMH1Myw
- name: prod-haproxy-user
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6InNsQU5mUmV2QkJrTHNhWE5QWmx2WTJQTDc5eWt4UXFEMEc1cjlFaGVURHMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJoYXByb3h5LXVzZXItdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiaGFwcm94eS11c2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMGRlZGM3NTQtZTdmOC00NzgyLTk1ZGMtMzk2ZWEwMGEyN2RjIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmhhcHJveHktdXNlciJ9.LvnmFLfSXur0ym7U3aKPkEER-eotidWjKRFjDMxlGlCFgPPs2I-YKi8phKfFgekGtSU8t6htOP66QzAFzGystcYRpxh-7TeqrxWcwjZ1ZC7_s2B_zt6Y58oxhNDY1kEkFGsnnKEFdJxSpMs5wfwL0H1HsdeMGhwrRs0mJ2Tca0wmwr5K--VXGqgG_jiFDhRZurix_L5ikeuCOCQ2srftKotTRpYJu5kJqcWBcXZOF2tHbE6xvyG7P30JgBFkdcyoAAXA-idFerzU9P0ttP1fxlB00fRnPcwO6iORBfT9wETv_34ETQQl_SvtVfLlaSqS5pfgm8o19ItiIvFhTy56gQ

current-context: dev

