replicaCount: 1

elasticsearch:
  protocol: https
  hosts: "elasticsearch-master"
  port: 9200
  auth:
    enabled: true
    username: elastic
    password:
      valueFrom:
        secretKeyRef:
          name: elasticsearch-es-elastic-user
          key: elastic

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

service:
  type: ClusterIP
