apiVersion: batch/v1
kind: CronJob
metadata:
  name: historical-weather
  namespace: apps
spec:
  schedule: "0 2 * * *"  # runs at 2:00 AM UTC daily
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: historical-weather
              image: your-registry/historical-weather:latest
              env:
                - name: INFLUXDB_URL
                  value: "http://influxdb.monitoring.svc.cluster.local:8086"
                - name: INFLUXDB_ORG
                  value: "virtualelephant"
                - name: INFLUXDB_BUCKET
                  value: "weather"
                - name: INFLUXDB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: influxdb-auth
                      key: token
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "100m"
                limits:
                  memory: "512Mi"
                  cpu: "250m"
          restartPolicy: Never
