apiVersion: v1
kind: Secret
metadata:
  name: influxdb-credentials
  namespace: signalwave
type: Opaque
stringData:
  INFLUX_TOKEN: nZHQrwn2ONAps6aCVCOtGx8OCdjfMIYfXU_iIOqsqyH4Ar0_SJNvPP9G4nswy-JhNvXvs74yKds5T5Rp1gmwsQ==
