apiVersion: apps/v1
kind: Deployment
metadata:
  name: signalwave-influx-reader
  namespace: signalwave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influx-reader
  template:
    metadata:
      labels:
        app: influx-reader
    spec:
      containers:
      - name: influx-reader
        image: harbor.home.virtualelephant.com/ve-lab/influx-reader:latest
        imagePullPolicy: Always
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq.services.svc.cluster.local"
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: RABBITMQ_USER
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: RABBITMQ_PASS
        - name: INFLUX_URL
          value: "http://influxdb.services.svc.cluster.local:8086"
        - name: INFLUX_TOKEN
          valueFrom:
            secretKeyRef:
              name: influxdb-credentials
              key: INFLUX_TOKEN
        - name: INFLUX_ORG
          value: "virtualelephant"
        - name: INFLUX_BUCKET
          value: "monitoring"
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: signalwave-influx-reader
  namespace: signalwave
spec:
  selector:
    app: influx-reader
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
