apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
  namespace: signalwave

spec:
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: publisher
        image: harbor.home.virtualelephant.com/ve-lab/publisher:latency
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: publisher
  namespace: signalwave
spec:
  selector:
    app: publisher
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
