apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq
  namespace: monitoring  # or wherever your Prometheus stack is
  labels:
    release: prometheus  # match your Prometheus release name
spec:
  selector:
    matchLabels:
      app: rabbitmq
  namespaceSelector:
    matchNames:
      - services
  endpoints:
    - port: metrics
      interval: 30s