apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rrdtool-pvc
  namespace: signalwave
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rrd-reader
  namespace: signalwave
  labels:
    app: rrd-reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rrd-reader
  template:
    metadata:
      labels:
        app: rrd-reader
    spec:
      containers:
      - name: rrd-reader
        image: harbor.home.virtualelephant.com/ve-lab/rrd-reader:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: rrd-storage
          mountPath: /app/rrd_files
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq.signalwave.svc.cluster.local"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: "deploy"
        - name: RABBITMQ_PASS
          value: "VMware123!"
        - name: RABBITMQ_QUEUE
          value: "signalwave"
      volumes:
      - name: rrd-storage
        persistentVolumeClaim:
          claimName: rrdtool-pvc
