apiVersion: apps/v1
kind: Deployment
metadata:
  name: rrd-reader
  namespace: signalwave
  labels:
    app: rrd-reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rrd-reader
  template:
    metadata:
      labels:
        app: rrd-reader
    spec:
      containers:
      - name: rrd-reader
        image: harbor.home.virtualelephant.com/ve-lab/rrdtool:v1.2
        imagePullPolicy: Always
        volumeMounts:
        - name: rrd-storage
          mountPath: /app/rrd_files
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq.signalwave.svc.cluster.local"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: "deploy"
        - name: RABBITMQ_PASS
          value: "VMware123!"
        - name: RABBITMQ_QUEUE
          value: "signalwave"
      volumes:
      - name: rrd-storage
        persistentVolumeClaim:
          claimName: shared-pvc
