apiVersion: v1
kind: PersistentVolume
metadata:
  name: rrdtool-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /opt/nfs/rrdtool
    server: 10.3.43.100
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rrdtool-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi