apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: cluster.local/nfs-subdir-external-provisioner
parameters:
  nfsServerHostname: 10.3.43.100
  nfsPath: /opt/nfs
