apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/deploy/.kube/dev-cluster-ca.crt
    server: https://10.5.1.13:6443
  name: dev
- cluster:
    certificate-authority: /home/deploy/.kube/stage-cluster-ca.crt
    server: https://10.5.1.15:6443
  name: stage
- cluster:
    certificate-authority: /home/deploy/.kube/prod-cluster-ca.crt
    server: https://10.5.1.17:6443
  name: prod

contexts:
- context:
    cluster: dev
    user: dev-haproxy-user
  name: dev
- context:
    cluster: stage
    user: stage-haproxy-user
  name: stage
- context:
    cluster: prod
    user: prod-haproxy-user
  name: prod

users:
- name: dev-haproxy-user
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ijl6YVNSRnZpaXNfdVBhTlc4cU5ldkp1b1RtNF9PV0IzdG5Cbm9TeTlNcjgifQ....
- name: stage-haproxy-user
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkZ3Z19yNHFvUlp6YmZxazdxdEdRWmszZ1gtZWltd2liOXBKVk5FbnNlTEUifQ....
- name: prod-haproxy-user
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6InNsQU5mUmV2QkJrTHNhWE5QWmx2WTJQTDc5eWt4UXFEMEc1cjlFaGVURHMifQ....

current-context: dev

